version: '3.9'
services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: measure-db
      DB_SYNCHRONIZE: true
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: measure-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"